name: static
type: 'nodejs:16'
build:
  flavor: none
hooks:
  build: bash ./static.platform.sh build
  deploy: bash ./static.platform.sh deploy
  post_deploy: bash ./static.platform.sh post_deploy
disk: 320
mounts:
  volume:
    source: local
    source_path: volume
web:
  # This is to start the node server to intercept all undefined route requests
  commands:
    start: node sites/canvasx-demo/404.js
  locations:
    /:
      root: public
      index:
        - index.html
      scripts: false
      allow: true
      expires: 6h
      headers:
        X-Frame-Options: SAMEORIGIN
        x-content-type-options: nosniff
        # content-security-policy: set in meta see gatsby-config.js
        X-XSS-Protection: 1; mode=block
        Referrer-Policy: strict-origin-when-cross-origin
        Permissions-Policy: geolocation=(), midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()
      passthru: true
      rules:
        \.(css|js|gif|jpe?g|png|ttf|webp|eot|woff2?|otf|cast|mp4|yaml|ico|svg?)$:
          expires: 4w
    # This is to invalidate route 404 so we can return a 404 status on it
    /404:
      root: sites/canvasx-demo/public
      index:
        - index.html
      allow: false
      passthru: true
    /___docs:
      expires: 6h
variables:
  env:
    APP_VOLUME: /app/volume
    APP_SITE_NAME: canvasx-demo
