language: node_js
node_js:
  - "10.16"
install: 
  - npm run setup
script:
  - BODILESS_DOCS_COPYFILES=1 npm run build 
  - npm run lint
  - npm run test
  - touch examples/test-site/doc/.nojekyll
deploy:
  local_dir: examples/test-site/doc
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
