name: Doc
env:
  CI: true
  FORCE_COLOR: 1

on:
  push:
    branches:
      - main

jobs:
  publish_doc:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v18.16
        uses: actions/setup-node@v1
        with:
          node-version: 18.16
      - name: Setup
        run: npm run setup
      - name: Site build
        run: npm run build -- --filter=@sites/test-site
      - name: Build docs
        run: npm run build:docs --workspace=@sites/test-site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sites/test-site/doc
