name: lerna-pr-canary-release
env:
  CI: true
  FORCE_COLOR: 1
  PR_NUMBER: ${{ github.event.number }}
  BUILD_NUMBER: ${{ github.run_number }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lerna-pr-canary-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Build
        run: npm run setup
      - name: Publish Canary Release
        run: >
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null &&
          npm run lerna publish --
          --canary
          --exact
          --preid=alpha-$PR_NUMBER.$BUILD_NUMBER
          --dist-tag=alpha-$PR_NUMBER.$BUILD_NUMBER
          --include-merged-tags
          --yes
