name: Prerelease
env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  push:
    branches:
      - main
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Build
        run: npm run setup
      - name: Setup git user
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Prerelease
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=beta --include-merged-tags --yes
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          npx lerna publish from-git --dist-tag=next --yes
      - name: Unset Git User
        run: |
          git config --unset user.name
          git config --unset user.email
