name: Test Workflow Listener

on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - 'upgrade/**'

jobs:
  on-label:
    permissions:
      pull-requests: write
    uses: johnsonandjohnson/Bodiless-JS/.github/workflows/build-test-lint-simple.yml@main
    secrets: inherit
    if: ${{ github.event.label.name == 'ready-to-test' || github.event.label.name == 'skip-tests' }}
