name: Test Workflow Listener

on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - 'upgrade/**'
      - 'test/starter-testing-temp'

jobs:
  on-label:
    permissions:
      checks: write
      pull-requests: write
    uses: johnsonandjohnson/Bodiless-JS/.github/workflows/build-test-lint-simple.yml@test/starter-testing
    secrets: inherit
    if: ${{ github.event.label.name == 'ready-to-test' || github.event.label.name == 'skip-tests' }}
